apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    environment: test
  name: test  
spec:
  replicas: 3
  selector:
    matchLabels:
      environment: test
  template:
    metadata:
      labels:
        environment: test
    spec:
      containers:
      - image: nginx:1.26.3     
        name: nginx 
